language: php
php:
  - 5.5
  - 5.6
  - 7.0
  - hhvm

before_script:
  - composer install
  - sh -c "cd vendor/twig/twig/ext/twig && phpize && ./configure --enable-twig && make && make install"
  - echo "extension=twig.so" >> `php --ini | grep "Loaded Configuration" | sed -e "s|.*:\s*||"`

script:
  - vendor/bin/phpspec run
  - phpunit
