language: php
php:
  - 7.0
  - 7.1
  - hhvm

matrix:
  allow_failures:
    - php: hhvm
    - php: 7.1


env:
  - COMPOSER_FLAGS='--prefer-stable'
  - COMPOSER_FLAGS=''

before_script:
  - composer install $COMPOSER_FLAGS --prefer-dist --no-interaction

script:
  - bin/phpspec run
  - bin/phpunit

cache:
  directories:
    - $HOME/.composer/cache
