language: php
php:
  - 7.1
  - 7.2
  - 7.3
  - nightly

matrix:
  allow_failures:
    - php: nightly

env:
  - COMPOSER_FLAGS='update --prefer-stable'
  - COMPOSER_FLAGS='install'

before_script:
  - composer $COMPOSER_FLAGS --prefer-dist --no-interaction

script:
  - bin/phpspec run
  - bin/phpunit

cache:
  directories:
    - $HOME/.composer/cache
