language: php
php:
  - 5.5
  - 5.6
  - nightly
  - hhvm

matrix:
  allow_failures:
    - php: hhvm
    - php: nightly

before_script:
  - composer install

script:
  - vendor/bin/phpspec run
  - phpunit